# ギルド・ヤドリギのトラブル対応ガイドライン
:toc:

## 概要

ギルド・ヤドリギ管理メンバーは、メンバーの皆さんがコミュニティ内において円滑に語り、遊び、創り、消費するために、コミュニティ内における行動は極力縛るべきではないと考えています。
しかし、ギルド・ヤドリギがコミュニティである以上、トラブルを完全に避ける事はできません。
そこで、ギルド・ヤドリギでは必要最低限と思われるルール(初めにお読みください/readme-first)を用意し、メンバーの皆さんにはその規約にしたがって頂く事により、円滑に運営することができています。

しかし、運営を続けて規模が大きくなっていくなかで、従来のルールだけでは、コミュニティを守りきれない事がわかってきました。
そこで、本ガイドラインでは、より柔軟にコミュニティ内でのトラブルに対応するために、以下の二点を明文化しました。

* トラブルと通報 : もし皆さんが、ルールだけでは判断できないようなトラブルに遭遇した場合に、何をしてはいけないか、あるいはどのように対応するべきか
* 管理メンバーによる判断と制裁 : もし、あるヤドリギメンバーの間でトラブルが発生した場合に、管理メンバーは何を基準に判断し、残念ながらメンバーの誰かに問題行動が見受けられた場合、どのようなプロセスで制裁を行うべきか

すでにお気づきの方もいるかもしれませんが、本ガイドラインは時として、管理メンバーが想定していないようなトラブルが発生した際に、明確な基準なくヤドリギ・メンバーに対して、ロールのはく奪やサーバーからの追放といった制裁を行えるようにするための免罪符として機能します。

この事に対し、不安を覚えるメンバーもいるかもしれません。
本来であれば、法律のように様々なシチュエーションを想定した完璧なルールを制定し、それを元にさまざまな判断を下すべきですが、ギルド・ヤドリギのコミュニティ規模でそこまでの規模のルールを制定し、運用するのは現実的ではありません。
そこで、あなたがトラブルの主犯であると疑われてしまった時に、一部のサーバー管理者の暴走による制裁を防ぐために、「制裁のルール」を明文化しました。
このガイドラインが公開された2022/7/2以降、ギルド・ヤドリギにおけるトラブルは、このルールに則って実施されることとなります。

## トラブルと通報

もし、あなたがギルド内で、自身では手におえないようなトラブルに遭遇した場合は、管理メンバーに報告し、判断を仰ぐべきです。決して問題を起こした当人の悪い噂を流したり、つま弾きにするなど、私刑のような行いをするべきではありません。
報告先は、管理メンバーの誰であっても構いません。管理メンバーはギルドメンバーの誰かから相談を受けた場合、報告内容は管理メンバー全員に共有されます。
以下は各メンバーの対応しやすい報告先となります

. ベイナイト
** Twitter: @BainiteKobo
** Discord: Bainite/ベイナイト#9758
. ちゅーん
** Twitter: @its_out_of_tune
** Discord: ちゅーんさんだよー#6476

ただし、管理メンバーが介入するのは、トラブルの規模が大きくなり、当人間での解決が困難だった場合のみであることを理解してください。また、その場合にも管理メンバーによって出来るのは、簡単な仲裁や、問題行為を行なうメンバーのDiscordサーバーからの追放程度であり、根本的な解決は関係者間でしかできないという事を理解してください。

なお、トラブル時の情報共有や判断を迅速にするために、管理メンバーからのフレンド申請には応じるようにしてください。
もしも、応じなかった場合は、管理メンバーによる議論にあなたの主張は反映されませんし、もしあなたがトラブルの主犯と疑われていた場合は、前述の通り警告なくロールの剥奪やキックといった制裁が行なわれる事となります。

## 管理メンバーによる判断と制裁

ギルド・ヤドリギにおける運用は、数名の管理メンバーによって実施されています。なぜ、ギルドマスターのベイナイトだけでなく、複数のメンバーが必要なのか疑問に思う方もいるでしょう。
それは、いかに優秀なリーダーであっても、すべての事象を正しく判断し、方針を決定することはできないからです。

ギルド・ヤドリギが大きな決断に迫られた時、管理メンバーの誰かが独断で行動することはありません。かならず、立場のことなる数人のメンバーによって議論し、その決断が本当に適切なのかどうか判断します。
たとえ、論理的には明確に本ガイドラインに反した行為が見受けられたとしても、自主性を尊重し、警告や制裁を行なわない場合もありますし、あなたの行動に一定の理由があると主張するのであれば、その主張が正当かどうか管理メンバーは十分な議論を行なうでしょう。
これは、ギルド発足当時から管理メンバー間で共有されてきた暗黙知であり、だからこそ、ギルド・ヤドリギはこのようなガイドラインが必要になるような規模まで成長することができました。

### 制裁のルール

この節は、管理メンバーがギルドメンバーに対して何らかの制裁を検討する際に守られなければならない、管理メンバーのためのルールです。
言いかえれば、もし何かトラブルが発生し、あなたがトラブルの主犯と疑われてしまった場合に、一人の管理メンバーの独断によって不当に制裁を受けてしまう事を防ぐための防波堤となりますし、もし管理メンバーが以下のルールに従っていないと考えられる場合は、ギルドメンバーにはそのことを指摘する権利があります。

. 制裁は、常に管理メンバーの総意として実行されなくてはいけません。例外を除き、制裁を行なう前には、かならずその処置について全管理メンバーの合意が必要です。
. ただし以下のような場合は、該当の管理メンバーを除いた全メンバーの合意により議論および制裁を行なう事ができます。
... 一部の管理メンバーが音信普通で、取りうるすべての手段を取っても連絡が取れなかった場合
... 管理メンバー自身がトラブルの渦中にあったり、関係者と親しい関係であり公正な判断が困難である場合
. 管理メンバーは、制裁の決断を下す前に、関係するギルドメンバーあるいはその他の関係者に対して可能な範囲で問い合わせを行ない、でき得る限り詳細な情報を集め、余す所なく共有されなくてはいけません。トラブルに関するある事実が議論に携わる一部の管理メンバーしか知らないという事があってはいけません。
. 管理メンバーによる判断は、常に公正でなくてはいけません。一部のメンバーの発言をうのみにして、間違った判断を行なうような事はあってはなりません。
. 管理メンバーによる制裁は、例外を除き必ず以下の順に則って段階的に行なわれなければなりません。たとえば、何の前ぶれもなくキックしたり、ソーシャルメディア上で名指しして問題行動に対する晒し行為を行なうような事は許されません。
.. DM等の手段によって警告を行ないます。
... この際に、対象者に言い分がある場合はそれを受け入れ、改めて管理メンバー間で議論した上で、判断が覆った場合は撤回し、受け入れられない場合はその旨を併記した再警告を行います。
.. それでも改められない場合、警告後、1週間程度ヤドリギ・メンバーのロールを剥奪します。
.. それでも改められない場合、DM等の手段によって最終警告と共に、再びヤドリギ・メンバーのロールを剥奪します
.. 最終警告を受けても尚改められない場合は、警告内容に則ってアカウントをキックします
. ただし以下のような場合は、ただちに権限が剥奪し、サーバーから追放する場合があります。
.. ギルドメンバーの心身が著しく危険に晒される場合
.. 最低限のギルドの運営ができない場合。たとえばロールを剥奪されたはらいせに、自己紹介チャンネルを荒らすような行為はこれに該当します。
.. 悪意を持って、計画的にギルドやギルドメンバーを貶めようとしている事が明らかな場合。
.. DMのためのフレンド申請に応じないなどの理由で、適切な手順での制裁が不可能あるいは困難な場合
.. 既に制裁によるキック済みのメンバーによるサブアカウントである事が発覚した場合
. 各処理の後には、管理メンバーはどのような処理を行ったか、なぜそのような判断に至ったかを記録し、後のトラブル対応に適用できるように常にアップデートします。これにより、管理メンバーの気まぐれや贔屓で処遇が変化するような事態を防ぎます。
